### ISSUE TITLE
Constitution des URL DCAT des organisations du catalogue Mégalis ?

### ISSUE THREAD

**Issue by lvinsonneau** [megalis-bretagne/catalogue-opendata#10]
Nous essayons de compléter dans le jeu de données Profils acheteurs l'URL DCAT de référence sur notre catalogue udata pour chacun de nos acheteurs.

L'URL des catalogues des organisations est de la forme [https://data-catalogue.megalis.bretagne.bzh/api/1/organizations/{org}/catalog.xml] (https://data-catalogue.megalis.bretagne.bzh/api/1/organizations/megalis-bretagne/catalog.xml) où org est est l'ID de l'organisation ou le "slug" de l'organisation.

Exemple pour le catalogue Morbihan Energie :

    https://data-catalogue.megalis.bretagne.bzh/api/1/organizations/62ab0b2d91e115bd9decea14/catalog.xml
    https://data-catalogue.megalis.bretagne.bzh/api/1/organizations/syndicat-departemental-d-energies-du-morbihan/catalog.xml

Pour la reproduirepour chacun de nos acheteurs, nous avons besoin de comprendre (pour la 2nde possibilité),  : comment vous faites pour générer le nom de l'organisation et quelle est votre source ? (dans l'exemple précédent, il s'agit de "syndicat-departemental-d-energies-du-morbihan") ?
@hhAdAhh @yguenneugues @syji35 : pourriez-vous nous éclairer ?

Merci d'avance

**Comment by hhAdAhh** [comment]
Bonjour @lvinsonneau,

Concernant les slug ils sont générés en utilisant la lib Slugify voici un exemple avec la gestion des accents:
'C\'est déjà l\'été.' => "c-est-deja-l-ete"
De plus, il y a un ajout d'un index si jamais il y a deux noms similaires:
- un-test
- un-test-2

Selon moi, le plus simple est d'aller récupérer son slug ou son ID par l'interface admin:
![image](https://github.com/megalis-bretagne/catalogue-opendata/assets/131772637/f9787e8c-0828-4d7a-8c94-193c69722f4d)

Puis en cliquant sur le nom de l'organisme on est redirigé vers sa page avec dans l'url son slug:

![image](https://github.com/megalis-bretagne/catalogue-opendata/assets/131772637/a48c773c-9e72-4c9a-b8c4-812393fb131e)

Est-ce que cela répond bien à tes interrogations?

**Comment by yguenneugues** [comment]
Vous pouvez aussi utiliser les api udata pour retrouver ces informations. La docs est ici: https://doc.data.gouv.fr/api/reference/

Exemple d'utilisation avec le critère de recherche megalis:
https://data-catalogue-preprod.megalis.bretagne.bzh/api/1/organizations/?page=1&page_size=20&q=megalis

**Comment by spelhate** [comment]
Merci @yguenneugues et @hhAdAhh 
Notre besoin est constituer un référentiel des organismes "Mégalis" de la forme : **siren** | **url_DCAT** 
L'API pourrait nous permettre de le faire si le siren est toujours présent dans les informations, comme sur l'exemple que tu fournis @yguenneugues 
```json
{
"description" : "Syndicat mixte de coopération territoriale pour le développement de l'administration électronique en Bretagne\nsiren : 253514491",
"slug" : "megalis-bretagne"
```

**Comment by yguenneugues** [comment]
normalement le siren sera présent pour tous les organismes creer depuis myec3

**Comment by spelhate** [comment]
Merci.

**Comment by lvinsonneau** [comment]
OK, merci @yguenneugues .
@Cridard : normalement, tu as tout ce qu'il faut pour les données profil acheteur. Je clos le ticket.
