### ISSUE TITLE
Affichage des noms des admins et RGPD

### ISSUE THREAD

**Issue by lvinsonneau** [megalis-bretagne/catalogue-opendata#3]
Nous nous posons des questions liées au RGPD dans la mise en place du catalogue régional.

Par défaut, les nom et prénom des administrateurs de chaque organisation sont affichés sur le site en mode déconnecté.
C'est également le cas pour data.gouv.fr, mais la différence sur le site Mégalis est que cela relève d'une démarche automatique où nous n'avons pas, à ce stade, explicitement demandé l'autorisation à chaque admin de chaque organisation.

Techniquement, et si nécessaire, est-ce possible de ne pas afficher les nom et prénom des admins d'une organisation ?

**Comment by hhAdAhh** [comment]
Bonjour @lvinsonneau 
J'ai remplacé le nom d'un administrateur et d'un utilisateur par "Administrateur Data-catalogue Mégalis" et "Utilisateur Data-catalogue Mégalis" lorsque l'on n'est pas connecté à data-catalogue.
Ce n'est pas le cas pour la partie discussion pour le moment. Il sera plus difficile de suivre une conversation si celle-ci a des utilisateurs qui ne sont pas nommé, mais je peux faire la même anonymisation si vous le souhaitez.

Est-ce que cela vous convient?

**Comment by hhAdAhh** [comment]
![image](https://user-images.githubusercontent.com/131772637/235131924-4dccabbf-116e-4041-984b-d37c04bfb1c5.png)

**Comment by lvinsonneau** [comment]
Merci @hhAdAhh : on va en reparler en point de suivi projet data mardi prochain, mais a priori (et à confirmer @ElodieTessier ), ça permet de minimiser les risques RGPD.

**Comment by hhAdAhh** [comment]
@lvinsonneau Actuellement, le nom est "caché" lorsque l'utilisateur n'est pas connecté mais il est visible lorsque l'utilisateur se connecte.
Aussi, pour l'instant le mécanisme de caché les noms n'est pas mis dans les fils de discussions. Est-ce que je dois mettre ce mécanisme en place dans les discussions aussi ? svp

**Comment by lvinsonneau** [comment]
@hhAdAhh : Suite discussion interne Mégalis : OK pour anonymiser de la même façon dans les discussions.

juste une précision : tu disais qu'en mode connecté, le nom serait visible : peux-tu nous préciser : c'est tous les noms de tous les admins du catalogue qui seront visibles quand un utilisateur se connectera ?

**Comment by hhAdAhh** [comment]
Bonjour @lvinsonneau
"c'est tous les noms de tous les admins du catalogue qui seront visibles quand un utilisateur se connectera " => En effet, lorsqu'un utilisateur est connecté il pourra voir le nom des admins (fonctionnellement je n'applique pas le remplacement du nom par "Administrateur catalogue Megalis" lorsque l'utilisateur est connecté)

**Comment by lvinsonneau** [comment]
OK @hhAdAhh , merci de cette précision. 
Je te laisse me redire quand la modification sur les listes de discussion est prête (anonymisation) pour qu'on puisse passer le ticket en prêt pour la Prod. Merci !

**Comment by hhAdAhh** [comment]
@lvinsonneau c'est bon pour la partie discussion

**Comment by lvinsonneau** [comment]
OK @hhAdAhh

**Comment by lvinsonneau** [comment]
Mis en prod. Je clos le ticket
