### ISSUE TITLE
Pas reçu de notification mail suite à une discussion s

### ISSUE THREAD

**Issue by lvinsonneau** [megalis-bretagne/catalogue-opendata#5]
pas reçu de notif (sur mon mail lydie.vinsonneau@megalis.bretagne.bzh, est-ce normal ? (j'en ai déjà reçu en provenance de data.gouv)
![image](https://user-images.githubusercontent.com/2498403/195781897-0571ceee-ad8f-474c-a6f5-34cb52baf4ae.png)

**Comment by lvinsonneau** [comment]
Test OK, mais réception du mail dans les spams.
@hhAdAhh : au cas où, y-a-t-il qqchose que l'on puisse améliorer ?

**Comment by hhAdAhh** [comment]
@lvinsonneau je viens de corriger le problème en pre-prod

De: | Mégalis Bretagne (pre-prod) <no-reply@megalis.bretagne.bzh>
-- | --
à: | test@test.fr
Date: | 11 mai 2023 09:43
Objet: | [MEGALIS BRETAGNE] Votre login et votre mot de passe.
Envoyé par: | megalis.bretagne.bzh
signé par: | megalis.bretagne.bzh


C'est désormais envoyé et signé par megalis.bretagne.bzh et non plus par un smtp SIB

**Comment by lvinsonneau** [comment]
OK, merci.
