### ISSUE TITLE
Page Conditions générales d'utilisation absente

### ISSUE THREAD

**Issue by lvinsonneau** [megalis-bretagne/catalogue-opendata#7]
Tout est dans l'objet.
Attendez-vous que l'on vous fournisse un texte ou est-ce un bug ?

**Comment by lvinsonneau** [comment]
https://data-catalogue.megalis.bretagne.bzh/fr/terms/

**Comment by hhAdAhh** [comment]
Bonjour @lvinsonneau,
Je viens de mettre à jour [data-catalogue-preprod.megalis.bretagne.bzh/fr/terms/](https://data-catalogue-preprod.megalis.bretagne.bzh/fr/terms/) avec les mentions légales du site mégalis [services.megalis.bretagne.bzh/credits-et-mentions-legales](https://services.megalis.bretagne.bzh/credits-et-mentions-legales/).
Je peux changer le texte selon vos besoins, n'hésitez pas à me faire un retour à ce sujet s'il vous plaît

**Comment by lvinsonneau** [comment]
Merci @hhAdAhh , je vois déjà des petites choses à modifier (ex. ce n'est pas Softeam ni wordpress), mais on refait une passe avec @ElodieTessier  et on te propose des corrections.

**Comment by lvinsonneau** [comment]
@hhAdAhh : voici la nouvelle page de mentions légales validée : https://nextcloud.megalis.bretagne.bzh/s/CNpz8xqLajzZrG8

**Comment by hhAdAhh** [comment]
@lvinsonneau est-ce que cela convient? https://data-catalogue-preprod.megalis.bretagne.bzh/fr/terms/

**Comment by lvinsonneau** [comment]
Ok @hhAdAhh

**Comment by lvinsonneau** [comment]
Mis en prod. OK
