### ISSUE TITLE
Pas possibilité de voir les données CSV sous forme d'un tableau comme sur data.gouv ?

### ISSUE THREAD

**Issue by lvinsonneau** [megalis-bretagne/catalogue-opendata#8]
Sur un jeu de données CSV (ex. délibération), on n'a plus la possibilité de visualiser le jeu de données (comme sur data.gouv) ?

**Comment by hhAdAhh** [comment]
Pour pouvoir prévisualiser les jeux de données CSV, il faut:

- Ajouter et configurer le plugin [udata-tabular-plugin](https://github.com/opendatateam/udata-tabular-preview)

- Déployer et configurer [csvapi](https://github.com/etalab/csvapi) dans notre environnement

**Comment by ElodieTessier** [comment]
OK, bien en prod
=> Done, je clos l'issue

![Image](https://github.com/megalis-bretagne/catalogue-opendata/assets/97222408/7e661c80-3ba2-4369-b3ab-2f0aa2c259ca)
