### ISSUE TITLE
Recherche d'une donnée par format non implémentée ?

### ISSUE THREAD

**Issue by lvinsonneau** [megalis-bretagne/catalogue-opendata#9]
![image](https://user-images.githubusercontent.com/2498403/195785648-5af55700-89f2-4b3a-a88f-67445340ddd4.png)

**Comment by gautierrog** [comment]
Avec la maj du catalogue, la recherche par format sera disponible ici:
![image](https://user-images.githubusercontent.com/110091547/234244367-0adadd86-155f-4da4-9701-a37ecfb23172.png)

**Comment by lvinsonneau** [comment]
OK @gautierrog  : je repasse juste en "Prêt pour installation en Prod" plutôt que "Done" (qui correspond à l'étape de validation côté Mégalis, une fois que c'est installé en prod
